## @section Global Parameters
## @param commonLabels.app common app label
## @param commonLabels.app.kubernetes.io/name common Kubernetes app label
## @param commonLabels.app.kubernetes.io/component common Kubernetes app component label
commonLabels:
  app: prometheus
  app.kubernetes.io/name: prometheus-federation
  app.kubernetes.io/component: prometheus

## @param serviceAccount.name name of service account
serviceAccount:
  name: prometheus-federation
    
## @param role.rules[0].apiGroups api groups rules
## @param role.rules[0].resources resources is applied
## @param role.rules[0].resourceNames resource name
## @param role.rules[0].verbs resources verbs is applied
role:
  rules:
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["http:prometheus-kube-prometheus-prometheus:9090"]
    verbs: ["get"]
