annotations:
  category: Infrastructure
apiVersion: v2
# Please make sure that version and appVersion are always the same.
appVersion: 1.10.0
description: A Library Helm Chart for grouping common logic between charts. This chart is not deployable by itself.
keywords:
  - common
  - helper
  - template
  - function
name: common
sources:
  - https://github.com/bitnami/charts
  - https://www.bitnami.com/
type: library
version: 1.10.3
