apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.labels }}
    {{toYaml .Values.labels | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
rules:
{{- if .Values.role.rules }}
{{ toYaml .Values.role.rules | indent 0 }}
{{- end }}

