{{- if .Values.image }}
{{- if .Values.image.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.secretName}} 
  annotations:
    description: "{{ .Chart.Description }}"
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" . }}
{{- end }}
{{- end }}