commonLabels:
  app: prometheus
  app.kubernetes.io/name: prometheus-federation
  app.kubernetes.io/component: prometheus

serviceAccount:
  name: prometheus-federation
  
role:
  rules:
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["http:prometheus-kube-prometheus-prometheus:9090"]
    verbs: ["get"]
