{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled .Values.metrics.serviceMonitor.basicAuth.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.labels.app }}-basic-auth
data:
  password: {{ .Values.metrics.serviceMonitor.basicAuth.user | b64enc }}
  user: {{ .Values.metrics.serviceMonitor.basicAuth.password | b64enc }}
type: Opaque
{{- end }}
