commonLabels:
  app: cluster-reader
  app.kubernetes.io/name: cluster-reader
  app.kubernetes.io/component: cluster-reader

serviceAccount:
  name: cluster-reader
  
clusterRole:
  rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
