name: Lint and Test Charts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Reference https://github.com/marketplace/actions/helm-chart-testing
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: .github/config/cf.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install
          config: .github/config/cf.yaml
